import type { Metadata } from "next";
import Topo from './ui/navbar'
import Rodape from './ui/footer'
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Topo/>
        </div>

        {children}
        
        <div>
          <Rodape/>
        </div>
        
      </body>
    </html>
  );
}
